[package]
name = "duet"
version = "0.1.0"
authors = ["Dmitriy Morozov <dmitriy@mrzv.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.5.1"
