[package]
name = "duet"
version = "0.1.0"
authors = ["Dmitriy Morozov <dmitriy@mrzv.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap  = "2.33.2"
colored = "2"
shellexpand = "2.0.0"
color-eyre = "0.5.1"
savefile = "0.7.2"
savefile-derive = "0.7.2"
log = "0.4.11"
env_logger = "0.7.1"
